export const languageDD = {
  en: "English",
  de: "Deutsch",
  es: "Español",
  fr: "Français",
  hi: "हिन्दी / Hindī",
  id: "Indonesian",
  it: "Italiano",
  pt: "Português",
  ru: "Русский",
  th: "ไทย",
  tr: "Türkçe",
  vi: "Tiếng Việt",
  ja: "日本語",
  ko: "한국어",
  ms: "Malay",
  ph: "Filipino",
  zhcn: "简体中文",
  zhtw: "繁體中文",
  ar: "العربية",
  bn: "বাঙালি"
};

export const homePath = "/";
export const mp3Path = "/youtube-to-mp3";
export const mp4Path = "/youtube-to-mp4";
export const searchPath = "/search";
export const convertPath = "/convert";

export const blockedIds = [
  "YVnTGDRXctA",
  "Rk2MW6L89mY",
  "LL0Njfd4oCk",
  "bloYQwsi0Q0",
  "XHdWkjtuW8M",
  "nVp-RXCloRg",
  "anpXyXmBzW8",
  "VQIJpTCgtek",
  "oWLym1xuLNM",
  "ONkLOc-0gH4",
  "HnsP76JsfqM",
  "fvLPaP1T8w0",
  "VQ5BmJ_oyBw",
  "_P7S2lKif-A",
  "oslzW2fEBr8",
  "RRkMbtbNBBs",
  "kI4xmwcfEw0",
  "OCioFrQ-pb8",
  "fYqeSZoNqqA",
  "jjrnZ3rHBAM",
  "PWmJhh_qTSY",
  "mkGDc9LQr6M",
  "68_RO1Z0548",
  "rNoL0n2WFh4",
  "RcagpuZ8frA",
  "cZ_wbu0ebvc",
  "9fNbjMXXYV4",
  "hbHw7noE0b4",
  "cBqRQqAqypM",
  "aKnyTRH6lRw",
  "vKQGTmaDy30",
  "kNlqMit92LI",
  "0Cuwgzbejdc",
  "XKoW06LRNGs",
  "AlXp0b9ckgs",
  "rJWdfDPZ9Ck",
  "pfxyk1glEq4",
  "jjrnZ3rHBAM",
  "dQw4w9WgXcQ",
  "qh78Rg89upM",
  "33T-Ub4XtAU",
  "z0rsohKGd-w",
  "jKbR7u8J5PU",
  "K7oav1IOVpk",
  "fUeoMS7EC7Q",
  "BNx2BKvte80",
  "nYpEc2-kfJY",
  "xo2-GVRNEro",
  "gD44wpQTLvw",
  "WsaDrHNt8IQ",
  "WbPeQXJAmts",
  "oacrqT9HAtk",
  "vBiOA84AuKc",
  "qhg7QXSXxeY",
  "ltIzQliz3XQ",
  "qkrrqTEH_zg",
  "soNakWWx5mU",
  "2Vv-BfVoq4g",
  "WcIcVapfqXw",
  "lYfrKmEYpdA",
  "EH7dT5w25AE",
  "opHgzTD851g",
  "_zfbIUbbKos",
  "6cU7xDHPQQY",
  "qKbKiRlMgOE",
  "orJSJGHjBLI",
  "JGwWNGJdvx8",
  "lp-EO5I60KA",
  "2Vv-BfVoq4g",
  "nSDgHBxUbVQ",
  "_dK2tDK9grQ",
  "FOjdXSrtUxA",
  "y83x7MgzWOA",
  "SuGWKuXYU0g",
  "f0aYZXsvdBQ",
];
