export const languageDD = [
  { code: "en", name: "English" },
  { code: "de", name: "Deutsch" },
  { code: "es", name: "Español" },
  { code: "fr", name: "Français" },
  { code: "hi", name: "हिन्दी / Hindī" },
  { code: "id", name: "Indonesian" },
  { code: "it", name: "Italiano" },
  { code: "ja", name: "日本語" },
  { code: "ko", name: "한국어" },
  { code: "my", name: "Myanmar (မြန်မာ)" },
  { code: "ms", name: "Malay" },
  { code: "ph", name: "Filipino" },
  { code: "pt", name: "Português" },
  { code: "ru", name: "Русский" },
  { code: "th", name: "ไทย" },
  { code: "tr", name: "Türkçe" },
  { code: "vi", name: "Tiếng Việt" },
  { code: "zh-cn", name: "简体中文" },
  { code: "zh-tw", name: "繁體中文" },
  { code: "ar", name: "العربية" },
  { code: "bn", name: "বাঙালি" },
];
